version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4
  python: circleci/python@2.1.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout     
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
              coverage run -m pytest
              coverage report
              coverage html
      - store_artifacts:
          path: htmlcov
workflows:
  sample:
    jobs:
      - build-and-test:
          post-steps:
            - codecov/upload      